# Generated by Django 3.2.5 on 2021-07-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('numeroBloques', models.IntegerField()),
                ('numeroHilos', models.IntegerField()),
                ('tiempoProcesamiento', models.FloatField()),
                ('mascara', models.IntegerField()),
                ('sigma', models.IntegerField()),
            ],
        ),
    ]
